# Generated by Django 4.2.2 on 2023-06-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='price',
            field=models.SmallIntegerField(blank=True, default=30, null=True, verbose_name='سعر ساعة الحجز'),
        ),
    ]
