# Generated by Django 4.2.2 on 2023-06-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_device_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
