# Generated by Django 4.2.2 on 2023-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_device_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(blank=True, choices=[('P3', 'بلايستيشن 3'), ('P4', 'بلايستيشن 4'), ('P5', 'بلايستيشن 5')], default='P4', max_length=2, null=True),
        ),
    ]
