# Generated by Django 4.2.2 on 2023-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_alter_device_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
