# Generated by Django 4.2.2 on 2023-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_rent_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='test',
            field=models.CharField(default='-- sasa -  as- ', max_length=15),
        ),
    ]
