# Generated by Django 4.2.2 on 2023-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_remove_rent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='العدد'),
        ),
    ]
